export const devskills = [
  "TypeScript",
  "CSS/SCSS",
  "HTML5",
  "React/NextJs/Gatsby",
  "HeadlessCMS",
  "Angular",
  "ArcGIS/Mapbox",
  "Shopify/HydrogenJS",
  "TailwindCSS",
  "Redux/NgRx",
  "NodeJs",
  "LLM & AI Tooling",
  "Firebase/Supabase",
  "MongoDB/PostgreSQL",
  "Framer/GSAP",
  "Adobe Suite/Figma",
];

export const otherSkills = [
  "Graphic Design",
  "Project Management",
  "Public Speaking",
  "Adobe Suite",
  "Sketch/Figma/XD",
  "Print Production",
  "Logo Design",
];

export const items = [
  {
    id: 1,
    year: "2023 - Present",
    client: "Consulting",
    url: "/images/project-images/credera.png",
    slug: "/credera",
    otherImages: [],
    title: "Credera",
    tagline: "senior XD consultant working across industries",
    description:
      "As a consultant with Credera, I helped lead the development of internal software for a large energy company operating across Texas and the Midwest. My work included real-time technician route optimization tools and technician management dashboards, contributing to a 600% increase in client revenue and elevating the account to a top-10 performer through consistent delivery and alignment with product strategy. Over 2.5 years, I worked across three products focused on increasing productivity, reducing technician drive time, and decreasing emergency response times.  ",
    tech: ["Angular", "ArcGIS", "Material", "SignalR", "NgRx"],
    category: "professional",
    github: null,
    link: "https://www.credera.com/en-us",
  },
  {
    id: 2,
    year: "2021",
    client: "NeoTreks",
    url: "/images/project-images/plow-ops.jpg",
    slug: "/plowops",
    otherImages: ["/images/project-images/plow-ops-1.jpg"],
    title: "Plow Ops",
    tagline: "innovative snow operations software",
    description:
      "PlowOps is one of the world's first snow plow tracking applications and it is sold to cities around the country. In my role, I was responsible for designing and developing the marketing website, as well as creating the user interface for the customer dashboard. This dashboard allows users to view real-time information about plow locations, report crashes, and track plow operators' progress. The dashboard's frontend was developed with Angular and Material, while the website was created with GatbsyJS, TailwindCSS, and AWS serverless functions. This project was for NeoTreks Inc, a software company based in Castle Rock, CO.",
    tech: ["Angular 10", "GatsbyJs", "Material", "TailwindCSS", "Figma"],
    category: "professional",
    github: null,
    link: "https://plowops.com/",
  },
  {
    id: 3,
    year: "2022",
    client: "Hartman Ely Investments",
    url: "/images/project-images/hartman-ely.jpg",
    slug: "/hartman-ely-investments",
    otherImages: [
      "/images/project-images/hartman-ely-1.jpg",
      "/images/project-images/hei-investments-lighthouse-1.png",
      "/images/project-images/hei-investments-lighthouse.png",
    ],
    title: "Hartman Ely Investments",
    tagline: "sustainable investment company website",
    description:
      "A full end-to-end build for a Boulder-based sustainable development company. Designed and developed solo using Next.js, Payload CMS, and Tailwind CSS, with 100% Lighthouse scores across every page.",
    tech: ["NextJS", "PayloadCMS", "TailwindCSS", "Figma"],
    category: "professional",
    github: "https://github.com/balthazarely/hartmanely.com",
    link: "https://www.hartmanely.com/",
  },
  {
    id: 4,
    year: "2026",
    client: "me",
    url: "/images/project-images/lifts-1.png",
    slug: "/lifts-workout-app",
    otherImages: [
      "/images/project-images/lifts-2.png",
      "/images/project-images/lifts-3.png",
    ],
    title: "Lifts Workout",
    tagline: "better workout tracking",
    description:
      "A full-stack fitness tracking application built with Next.js, Supabase, and the AI SDK. I built this to encorporate features that I wanted in my training routine, such as quick workout builder, AI workout features, and the ability to add custom exercises. Users can log workouts from a curated exercise library organized by muscle group, equipment, and movement pattern, with support for preferred weight units. The app leans heavily on Next.js server components — workout data, user profiles,  and exercise lists are all fetched server-side, with React Suspense used to stream dashboard charts independently without blocking page render. Workout history is persisted per user via Supabase Auth and a Postgres backend. The app integrates Anthropic's AI SDK for intelligent workout suggestions. Built with shadcn/ui, TailwindCSS v4, and Zod for schema validation, with a seed script for populating the exercise database.",
    tech: [
      "NextJs",
      "Supabase",
      "Shadcn/ui",
      "Server-Side Rendering",
      "AI SDK",
      "Zod",
    ],
    category: "personal",
    github: "https://github.com/balthazarely/ssr-auth-example",
    link: "https://ssr-auth-example.vercel.app",
  },
  {
    id: 5,
    year: "2026",
    client: "me",
    url: "/images/project-images/epic-ikon-1.png",
    slug: "/epic-ikon",
    otherImages: ["/images/project-images/epic-ikon-2.png"],
    title: "Epic vs Ikon",
    tagline: "explore the ski slopes",
    description:
      "I developed Epic vs Ikon, an interactive web application for exploring ski resorts across the world through a real-time 3D globe visualization. Built with Next.js, React, Three.js, Mapbox GL, and TailwindCSS, the app allows skiers to discover and compare resorts across North America, Japan, and Australia — with rich filtering by pass type (Ikon and Epic), vertical drop, trail count, and lift access. At the core of the app is a custom Three.js globe with sprite-based resort markers, intelligent proximity clustering, and smooth animated camera transitions. I implemented a canvas-based texture generation system for cluster badges and glow effects, avoiding pre-rendered assets in favor of dynamic rendering. Detailed resort data — including trail difficulty breakdowns, lift infrastructure, and snowmaking coverage — is surfaced in a drawer view powered by streaming API routes and React Query for efficient caching. Considerable attention went into interaction design: the globe supports drag-to-rotate, region fly-to animations, and an eased intro camera arc on load. The app is fully responsive, with a dedicated mobile filter drawer and layout optimizations for smaller screens.",
    tech: ["React", "Three.js", "TailwindCSS", "Tanstack"],
    category: "personal",
    github: "https://github.com/balthazarely/epic-ikon",
    link: "https://epic-ikon.vercel.app/",
  },

  {
    id: 6,
    year: "2021",
    client: "NeoTreks",
    url: "/images/project-images/accuterra.jpg",
    slug: "/accuterra",
    otherImages: [
      "/images/project-images/accuterra-1.jpg",
      "/images/project-images/accuterra-2.jpg",
    ],
    title: "AccuTerra",
    tagline: "website for AccuTerra map overlay",
    description:
      "This website is for AccuTerra Maps, which is a map overlay that is used by a variety of different apps and websites. Accuterra is geared towards outdoor recreations, and offers extensive national park data to its users. This project was built using Gatsby and incorporates maps from Mapbox, MapLibre, Google Maps, Leaflet, and ArcGIS. This project was for NeoTreks Inc, a software company based in Castle Rock, CO.",
    tech: ["GatsbyJs", "Mapbox"],
    category: "professional",
    github: null,
    link: "https://accuterra.com/",
  },
  {
    id: 7,
    year: "2026",
    client: "me",
    url: "/images/project-images/snow-agent.png",
    slug: "/snowagent",
    otherImages: [
      "/images/project-images/snow-agent-1.png",
      "/images/project-images/snow-agent-2.png",
      "/images/project-images/snow-agent-3.png",
      "/images/project-images/snow-agent-4.png",
    ],
    title: "Snow Agent",
    tagline: "find out where to ski this weekend",
    description:
      "I developed SnowAgent, a full-stack Colorado ski resort tracking app built with Next.js, React, TypeScript, and Tailwind CSS. The app answers a skier's most important morning question - where should I ski today? - by combining real-time snow data, personalization, and AI-powered recommendations. The app scrapes live conditions from OnTheSnow using Cheerio, caches the results in Redis via a cron-triggered pipeline, and surfaces snowfall totals, base depth, open trails, and lift counts across Colorado resorts. Users can filter by ski pass (Epic/Ikon), sort by new snow, bookmark favorites, and explore resorts on an interactive Mapbox map with color-coded snow depth indicators. To go beyond raw data, I integrated the Anthropic Claude API in two ways: a conversational Snow Agent that answers natural language questions about where to ski based on current conditions and the user's location, and a daily AI-generated Morning Report that delivers a punchy headline, best-bet resort pick, and worst-pick warning each morning at 6am MT. The app is also a fully functional PWA with service worker caching for offline access.",
    tech: ["Next.js", "PWA", "Web Scraping", "Cherrio", "Mapbox", "Redis"],
    category: "personal",
    github: "https://github.com/balthazarely/snow-scrapper",
    link: "https://snow-scrapper.vercel.app/",
  },
  {
    id: 8,
    year: "2022",
    client: "me",
    url: "/images/project-images/songdive.jpg",
    slug: "/songdive",
    otherImages: ["/images/project-images/songdive-1.jpg"],
    title: "Song Dive",
    tagline: "create playlists based on what you love",
    description:
      "I developed Song Dive, a comprehensive full-stack web application utilizing various  technologies such as the Spotify API, React, ExpressJS, and TailwindCSS. The app enables users to log in, view their favorite songs, create personalized playlists based on their listening habits or genre preferences, and search for music from Spotify's vast collection. To ensure that the app meets Spotify's design standards, it underwent a thorough review process with Spotify and was officially granted an extended quota. \n\nTo enhance user experience, I employed Framer Motion to achieve seamless page transitions and animations throughout the app. I dedicated considerable effort towards creating an intuitive UI with clean interaction, optimized loading states, and well-timed animations.",
    tech: ["React", "ExpressJS", "Spotify API", "TailwindCSS"],
    category: "personal",
    github: "https://github.com/balthazarely/playlist-last",
    link: "https://song-dive.herokuapp.com/",
  },

  {
    id: 9,
    year: "2023",
    client: "me",
    url: "/images/project-images/portfolio.jpg",
    slug: "/portfolio",
    otherImages: ["/images/project-images/portfolio-1.jpg"],
    title: "Portfolio",
    tagline: "2023 Potfolio",
    category: "personal",
    description:
      "This is the newest iteration of my portfolio, which I usually rebuild with once a year. I tried to put most of my time into making a smooth and responsive experience, as well as add a couple fun features. All the animations were done with Framer Motion, with some help with TailwindCSS.",
    type: "Website",
    tech: ["NextJS", "Framer Motion", "DaisyUI", "TailwindCSS"],
    github: "https://github.com/balthazarely/portfolio-2023-next",
    link: null,
  },
  {
    id: 10,
    year: "2022",
    client: "Freebird",
    url: "/images/project-images/freebird.jpg",
    title: "Freebird Shoes",
    slug: "/freebird",
    tagline: "high end women's shoes with Colorado flare.",
    description:
      "Freebird Shoes creates unique handcrafted boots and footwear, and runs a large ecommerce site based in Shopify, My work included writing custom Javascript/jQuery/Liquid to make custom features, integrating Yotpo/Klaviyo plugins, and creating a fully functioning Hydrogen (Shopify's React framework) shop, which used  GraphQL to interface with the Storefront API, Sanity CMS for static page data, and TailwindCSS for styling.",
    tech: ["Shopify", "HydrogenJS", "jQuery", "GraphQL", "SanityCMS"],
    category: "professional",
    github: null,
    link: "https://www.freebirdstores.com/",
  },
  {
    id: 11,
    year: "2019 - 2021",
    client: "Dish Network/OneTen Creative",
    url: "/images/project-images/one-ten.png",
    title: "OneTen Creative",
    slug: "/one-ten",
    tagline: "DCO animated banners",
    description:
      "I created this portfolio site to showcase a selection of HTML5 web banners that I developed during my tenure at OneTen Creative/DISH Network. Using React as the framework and GSAP, CSS animations, and HTML Canvas as the tools, I crafted engaging and dynamic animations for banner sets in six different sizes, catering to both mobile and desktop users. These banners were designed for DISH and its affiliates, such as OnTech, SlingTV, and DISH Latino.\n\n Employing dynamic creative optimization (DCO), I ensured that the banners were flexible enough to undergo copy and image changes even after going live for testing purposes. While working at DISH/OneTen Creative, I spearheaded an initiative to update and optimize the banners, incorporating new ES6 features, HTML Canvas, and dynamic variables to GSAP animations. As a result, the average development time per banner set decreased from a week to just a day. ",
    tech: ["GSAP", "CSS Animation", "HTML Canvas", "DCO"],
    category: "professional",
    github: "https://github.com/balthazarely/bannerbox_2020",
    link: "https://bannerbin-552ae.web.app/",
  },

  {
    id: 12,
    year: null,
    client: null,
    url: "/images/project-images/logos.jpg",
    slug: "/logos",
    otherImages: [
      "/images/project-images/logos-1.jpg",
      "/images/project-images/logos-2.jpg",
      "/images/project-images/logos-3.jpg",
      "/images/project-images/logos-4.jpg",
      "/images/project-images/logos-5.jpg",
      "/images/project-images/logos-6.jpg",
      "/images/project-images/logos-7.jpg",
      "/images/project-images/logos-8.jpg",
      "/images/project-images/logos-9.jpg",
      "/images/project-images/logos-10.jpg",
      "/images/project-images/logos-11.jpg",
      "/images/project-images/logos-12.jpg",
      "/images/project-images/logos-13.jpg",
      "/images/project-images/logos-14.jpg",
      "/images/project-images/brochures.jpg",
      "/images/project-images/brochures-1.jpg",
      "/images/project-images/brochures-2.jpg",
      "/images/project-images/brochures-3.jpg",
      "/images/project-images/brochures-4.jpg",
      "/images/project-images/brochures-5.jpg",
      "/images/project-images/brochures-6.jpg",
      "/images/project-images/brochures-7.jpg",
      "/images/project-images/brochures-8.jpg",
      "/images/project-images/branding-1.jpg",
      "/images/project-images/branding-2.jpg",
      "/images/project-images/branding-3.jpg",
    ],
    title: "Logos & Design",
    tagline: "various design projects from the past",
    description:
      "These are a collection of various design projects I have designed over the last few years for various clients.",
    tech: ["Photoshop", "InDesign", "Illustrator", "Lightroom"],
    category: "design",
    github: null,
    link: null,
  },
  {
    id: 13,
    year: null,
    client: null,
    slug: "/brochures",
    url: "/images/project-images/branding.jpg",
    otherImages: [
      "/images/project-images/brochures.jpg",
      "/images/project-images/brochures-1.jpg",
      "/images/project-images/brochures-2.jpg",
      "/images/project-images/brochures-3.jpg",
      "/images/project-images/brochures-4.jpg",
      "/images/project-images/brochures-5.jpg",
      "/images/project-images/brochures-6.jpg",
      "/images/project-images/brochures-7.jpg",
      "/images/project-images/brochures-8.jpg",
      "/images/project-images/branding-1.jpg",
      "/images/project-images/branding-2.jpg",
      "/images/project-images/branding-3.jpg",
    ],
    title: "Branding",
    tagline: "various brochures from the past",
    description:
      "These are a collection of various brochures I have designed over the last few years for various clients.",
    tech: ["Photoshop", "InDesign", "Illustrator", "Lightroom"],
    category: "design",
    github: null,
    link: null,
  },
];
