export const devskills = [
  "JavaScript",
  "CSS/SCSS",
  "HTML5",
  "React",
  "NextJs/Gatsby",
  "HydrogenJS",
  "Angular",
  "GraphQL",
  "Shopify",
  "TailwindCSS",
  "Bootstrap",
  "Express JS",
  "Firebase",
  "MongoDB",
  "Framer Motion",
  "GSAP",
];

export const otherSkills = [
  "Graphic Design",
  "Project Management",
  "Public Speaking",
  "Adobe Suite",
  "Sketch/Figma/XD",
  "Print Production",
  "Logo Design",
];

export const projectsForHomePage = [
  {
    name: "Plow Ops",
    category: "professional",
    type: "Website/Web App",
    tech: ["Angular 10", "GatsbyJs", "Material UI", "TailwindCSS"],
    image: "/images/project-thumbnails/plow-ops.jpeg",
    id: 0,
  },
  {
    name: "Hartman Ely Investments",
    category: "professional",
    type: "Website",
    tech: ["NextJS", "TailwindCSS"],
    image: "/images/project-thumbnails/hei.jpeg",
    id: 1,
  },
  {
    name: "AccuTerra",
    category: "professional",
    type: "Website",
    tech: ["GatsbyJs", "Maps"],
    image: "/images/project-thumbnails/accuterra.jpg",
    id: 2,
  },
  {
    name: "Song Dive",
    category: "personal",
    type: "Web App",
    tech: ["React", "ExpressJS", "Spotify API", "TailwindCSS"],
    image: "/images/project-thumbnails/songdive.jpeg",
    id: 3,
  },
  {
    name: "MovieBin",
    category: "personal",
    type: "Web App",
    tech: ["NextJS", "Firebase", "API", "TailwindCSS"],
    image: "/images/project-thumbnails/plow-ops.jpeg",
    id: 4,
  },
  {
    name: "Freebird Shoes",
    category: "professional",
    type: "Website/Eccomerce",
    tech: ["Shopify", "HydrogenJS", "jQuery", "GraphQL", "SanityCMS"],
    image: "/images/project-thumbnails/freebird.png",
    id: 5,
  },
  {
    name: "Privett Hachery",
    category: "professional",
    type: "Web App",
    tech: ["Angular 10", "Bootstrap"],
    image: "/images/project-thumbnails/privett.png",
    id: 6,
  },
  {
    name: "Identity Records",
    category: "personal",
    type: "Web App",
    tech: ["GatsbyJs", "Styled Components", "SanityCMS"],
    image: "/images/project-thumbnails/identity-records.jpeg",
    id: 7,
  },
  ,
  {
    name: "Bannerbox",
    category: "professional",
    type: "Web App",
    tech: ["React", "Firebase", "GSAP", "HTML Canvas", "DCO"],
    image: "/images/project-thumbnails/bannerbox.jpeg",
    id: 8,
  },
  {
    name: "Logos",
    category: "design",
    type: "Graphic Design",
    tech: ["Illustrator"],
    image: "/images/project-thumbnails/logos.jpeg",
    id: 9,
  },
  {
    name: "Brochures",
    category: "design",
    type: "Graphic Design",
    tech: ["Photoshop", "InDesign", "Illustrator", "Lightroom"],
    image: "/images/project-thumbnails/brochures.jpeg",
    id: 10,
  },
  {
    name: "Branding",
    category: "design",
    type: "Graphic Design",
    tech: ["Photoshop", "InDesign", "Illustrator", "Lightroom"],
    image: "/images/project-thumbnails/branding.jpeg",
    id: 11,
  },
];
